### ISSUE TITLE
Break Learn page into components

### ISSUE THREAD

**Issue by spences10** [chingu-voyage3/grad.then#25]
# discussion piece

![image](https://user-images.githubusercontent.com/234708/33902436-e945fe10-df6c-11e7-9099-6355c7ff3f23.png)

We need to identify components that are unique to this page and one that can be used in the app.

**Comment by spences10** [comment]
![image](https://user-images.githubusercontent.com/234708/33945374-bef5007a-e016-11e7-8418-0548c811ffe7.png)

## Components

* Course Card
* Course Card container
* Divider
* Search
* Filters - @mar-bi  are Search and Filters the same component?
* ?? can you identify this pls @mar-bi  😁

**Comment by mar-bi** [comment]
You are right with components. 👌
I plan to put **filter**, which is basically an inline list of links, together with **search*  in one container. 
So that, the user can have a quick access to meaningful groups of data or search for a paticular subject.
This pattern (**filter** with **search**) I used through the pages. It might be logical to assign it one component.

**Comment by mar-bi** [comment]
This is the same list as `jobs list` from #23.
Just the list items are **thinner` :smile:

**Comment by spences10** [comment]
closing now, components listed on #21
