### ISSUE TITLE
Divider Component

### ISSUE THREAD

**Issue by asanhix** [chingu-voyage3/grad.then#48]
Maybe we can base our divider component as in the following example https://shoutem.github.io/docs/ui-toolkit/components/dividers

**Comment by mar-bi** [comment]
These are our dividers:

1. Divider with text
![didvider-with-text](https://user-images.githubusercontent.com/25195616/34043801-470f4d22-e1ab-11e7-82c8-ac2c2161c371.png)

2. Divider with icons (yes, that's it. we need more icons :upside_down_face: )

![didvider-with-icons](https://user-images.githubusercontent.com/25195616/34043817-548d39d2-e1ab-11e7-9f0b-2d7d996d4908.png)

The last one is quite popular right now. 
(I guess, because users like big numbers :sunglasses: and underestimate how someone can use the power of statistics to fool people. :worried: We are not going to do this :upside_down_face: ) 
Many sites show how many:
- happy customers they served,
- projects launched,
- cups of coffee drank...

It would be nice to create some dummy and funny numbers for a purpose of the decoration.

**Technical details for `Divider`**
 - container (takes the full width of the page, all 12 columns): 
   - contains 1 column and  `<h3> or <p>`
   - contains 3 columns and 3 child containers with `icon` and `<p>` in each of them

**Comment by mar-bi** [comment]
@asanhix , I like the divider you suggested. :+1: 
I found this library is built on top of **ReactNative**. Right?

**Comment by asanhix** [comment]
@mar-bi yes  I found it w/ google search and believe we can replicate the functionality its is like a micro layout. We can keep it simple and if necessary build upon it.  :)

**Comment by mar-bi** [comment]
@asanhix , I've got your idea and I like it. :+1: 
React has this cool feature - [conditional rendering](https://reactjs.org/docs/conditional-rendering.html).
Maybe you can try to figure out how to build this *micro layout* for `Divider Component` in `Gatsby`. (yes, it's challenging :nerd_face: )

**Conclusion**: Would you like to start building this component? :wink: :upside_down_face:

**Comment by asanhix** [comment]
Thanks. :) sure @mar-bi  I will happily start to build it. :)

**Comment by spences10** [comment]
Closed with #68
